export const categories = [
  { id: "tiles", name: "Tiles" },
  { id: "kitchen", name: "Kitchen" },
  { id: "bathware", name: "Bathware" },
  { id: "surface", name: "Surface" },
  { id: "heatpump", name: "Heat Pump" },
  { id: "sinks", name: "Sinks" },
]

export const products = [
  {
    id: "1",
    name: "Premium Ceramic Floor Tiles",
    description: "High-quality ceramic tiles perfect for living rooms and bedrooms. Water-resistant and durable.",
    price: 45,
    stock: 150,
    category: "tiles",
    rating: 4.5,
  },
  {
    id: "2",
    name: "Marble Kitchen Countertop",
    description: "Elegant marble countertop for modern kitchens. Heat-resistant and easy to clean.",
    price: 12500,
    stock: 8,
    category: "kitchen",
    rating: 4.8,
  },
  {
    id: "3",
    name: "Luxury Bathroom Faucet Set",
    description: "Complete bathroom faucet set with modern design. Chrome finish with lifetime warranty.",
    price: 3200,
    stock: 25,
    category: "bathware",
    rating: 4.6,
  },
  {
    id: "4",
    name: "Granite Surface Slab",
    description: "Premium granite surface ideal for countertops and flooring. Polished finish.",
    price: 8500,
    stock: 12,
    category: "surface",
    rating: 4.7,
  },
  {
    id: "5",
    name: "Energy Efficient Heat Pump",
    description: "High-efficiency heat pump for residential use. Eco-friendly and cost-effective.",
    price: 45000,
    stock: 5,
    category: "heatpump",
    rating: 4.9,
  },
  {
    id: "6",
    name: "Stainless Steel Kitchen Sink",
    description: "Double bowl stainless steel sink with sound dampening. Perfect for modern kitchens.",
    price: 6500,
    stock: 18,
    category: "sinks",
    rating: 4.4,
  },
  {
    id: "7",
    name: "Porcelain Wall Tiles",
    description: "Beautiful porcelain tiles for bathroom and kitchen walls. Easy to maintain.",
    price: 65,
    stock: 200,
    category: "tiles",
    rating: 4.3,
  },
  {
    id: "8",
    name: "Modular Kitchen Cabinet Set",
    description: "Complete modular kitchen cabinet system with soft-close hinges and drawers.",
    price: 25000,
    stock: 6,
    category: "kitchen",
    rating: 4.7,
  },
  {
    id: "9",
    name: "Shower Enclosure Glass",
    description: "Tempered glass shower enclosure with chrome fittings. Modern and sleek design.",
    price: 15000,
    stock: 10,
    category: "bathware",
    rating: 4.5,
  },
  {
    id: "10",
    name: "Quartz Surface Counter",
    description: "Engineered quartz surface with consistent pattern. Non-porous and stain-resistant.",
    price: 9500,
    stock: 15,
    category: "surface",
    rating: 4.8,
  },
  {
    id: "11",
    name: "Smart Heat Pump Controller",
    description: "WiFi-enabled heat pump with smart controls and energy monitoring.",
    price: 52000,
    stock: 3,
    category: "heatpump",
    rating: 4.6,
  },
  {
    id: "12",
    name: "Undermount Bathroom Sink",
    description: "Elegant undermount sink for bathroom vanities. Ceramic construction with overflow.",
    price: 4200,
    stock: 22,
    category: "sinks",
    rating: 4.4,
  },
  {
    id: "13",
    name: "Mosaic Decorative Tiles",
    description: "Colorful mosaic tiles perfect for accent walls and backsplashes.",
    price: 85,
    stock: 0,
    category: "tiles",
    rating: 4.2,
  },
  {
    id: "14",
    name: "Kitchen Island with Storage",
    description: "Spacious kitchen island with built-in storage and breakfast bar.",
    price: 18000,
    stock: 4,
    category: "kitchen",
    rating: 4.9,
  },
  {
    id: "15",
    name: "Rainfall Shower Head",
    description: "Large rainfall shower head with adjustable flow settings. Chrome finish.",
    price: 2800,
    stock: 30,
    category: "bathware",
    rating: 4.5,
  },
  {
    id: "16",
    name: "Laminate Surface Flooring",
    description: "Durable laminate flooring with wood-look finish. Easy installation.",
    price: 120,
    stock: 80,
    category: "surface",
    rating: 4.1,
  },
]
